import Head from "next/head";
import styles from "../styles/Home.module.css";
import LeafletMap from "./LeafletMap";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alter Map with leaflet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LeafletMap />
    </div>
  );
}
